name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: setup
      run: sudo apt update && sudo apt install -y make gcc libcriterion-dev

    - name: test
      run: make test
